name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:     # Allows you to click a button to run it manually

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.STATS_TOKEN }}

      - name: Generate Stats Card
        uses: soulteary/github-readme-stats-action@v1.1.0
        with:
          card: stats
          options: 'username=leekahung&show_icons=true&theme=dark'
          path: github-stats.svg
          token: ${{ secrets.STATS_TOKEN }}

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add github-stats.svg
          git commit -m "docs: update github profile stats" || exit 0
          git push
