name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *' # Automatically runs every night at midnight
  workflow_dispatch:     # Allows you to click "Run workflow" manually

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.STATS_TOKEN }}

      - name: Generate Main Stats Card
        uses: soulteary/github-readme-stats-action@v1.0.0
        with:
          card: stats
          options: 'username=leekahung&show_icons=true&theme=dark'
          path: github-stats.svg
          token: ${{ secrets.STATS_TOKEN }}

      - name: Generate Top Languages Card
        uses: soulteary/github-readme-stats-action@v1.0.0
        with:
          card: top-langs
          options: 'username=leekahung&hide=jupyter%20notebook&layout=compact&theme=dark'
          path: top-langs.svg
          token: ${{ secrets.STATS_TOKEN }}

      - name: Save Changes to Repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add github-stats.svg top-langs.svg
          # The 'exit 0' ensures the workflow doesn't fail if stats haven't changed
          git commit -m "docs: auto-update github profile stats" || exit 0
          git push
